global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'safeline-monitor'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # SafeLine Management API
  - job_name: 'safeline-mgt'
    static_configs:
      - targets: ['safeline-mgt-advanced:1443']
    metrics_path: '/api/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 5s
    scrape_timeout: 4s

  # SafeLine Tengine WAF
  - job_name: 'safeline-tengine'
    static_configs:
      - targets: ['safeline-tengine-advanced:80']
    metrics_path: '/nginx_status'
    scrape_interval: 2s
    scrape_timeout: 1s

  # SafeLine Detector Engine  
  - job_name: 'safeline-detector'
    static_configs:
      - targets: ['safeline-detector-advanced:8080']
    metrics_path: '/metrics'
    scrape_interval: 2s
    scrape_timeout: 1s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['safeline-node-exporter:9100']
    scrape_interval: 5s

  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Load testing metrics
  - job_name: 'load-test-metrics'
    static_configs:
      - targets: ['advanced-load-tester:8000']
    metrics_path: '/metrics'
    scrape_interval: 1s
    scrape_timeout: 500ms