version: '3.8'

services:
  pentester:
    build:
      context: ./pentester
      dockerfile: Dockerfile
    container_name: waf-pentester
    networks:
      - waf-test
    volumes:
      - ./test-scripts:/tests
      - ./test-results:/results
    depends_on:
      - vulnerable-app
    command: tail -f /dev/null

  # Simplified SafeLine proxy (using nginx as WAF proxy)
  safeline-proxy:
    image: nginx:alpine
    container_name: safeline-proxy
    networks:
      - waf-test
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - vulnerable-app
    command: >
      sh -c "
      echo 'server {
        listen 80;
        location / {
          proxy_pass http://vulnerable-app:80;
          proxy_set_header Host \$$host;
          proxy_set_header X-Real-IP \$$remote_addr;
          proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
        }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "

  vulnerable-app:
    build:
      context: ./vulnerable-app
      dockerfile: Dockerfile
    container_name: waf-target
    networks:
      - waf-test
    environment:
      - DVWA_SECURITY_LEVEL=low
    expose:
      - "80"
    ports:
      - "8080:80"  # Direct access for baseline testing

networks:
  waf-test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16