version: '3.8'

services:
  # Simple vulnerable web server
  vulnerable-app:
    image: httpd:alpine
    container_name: vulnerable-target
    ports:
      - "8080:80"
    volumes:
      - ./simple-web:/usr/local/apache2/htdocs
    networks:
      - test-net

  # Simple proxy for testing (representing WAF)
  test-proxy:
    image: nginx:alpine
    container_name: test-proxy
    ports:
      - "8090:80"
    volumes:
      - ./proxy-config:/etc/nginx/conf.d
    depends_on:
      - vulnerable-app
    networks:
      - test-net
    command: >
      sh -c "
      echo 'server {
        listen 80;
        location / {
          proxy_pass http://vulnerable-target:80;
          proxy_set_header Host \$$host;
          proxy_set_header X-Real-IP \$$remote_addr;
        }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "

  # Load testing container
  load-tester:
    image: alpine:latest
    container_name: load-tester
    networks:
      - test-net
    volumes:
      - ./test-scripts:/scripts
      - ./test-results:/results
    depends_on:
      - vulnerable-app
      - test-proxy
    command: >
      sh -c "
      apk add --no-cache curl apache2-utils python3 py3-pip &&
      pip3 install requests &&
      tail -f /dev/null
      "

networks:
  test-net:
    driver: bridge